import{a as d,i as g}from"./assets/vendor-6d0036ef.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="https://api.thecatapi.com/v1/breeds",L="live_1BhCbAxOfyNpYIgTYCWiXZS6lDLk1jq88WQSVrpMPuPstv7Ox0sVSsaxQgcHHrTK";d.defaults.headers.common["x-api-key"]=L;function b(){return d.get(S).then(n=>n.data)}function v(n){const o="https://api.thecatapi.com/v1/images/search";return d.get(o,{params:{breed_ids:n}}).then(s=>s.data)}document.addEventListener("DOMContentLoaded",function(){const n={breedSelect:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader")},o=new SlimSelect({select:n.breedSelect,placeholder:"Select a breed",showSearch:!0,searchText:"No matches found",searchPlaceholder:"Search...",searchHighlight:!0,searchFocus:!0,allowDeselect:!1,onChange:s});function s(){const e=o.selected();e&&u(),v(e).then(a).catch(c=>m(c)).finally(()=>{e&&(f(),h())})}function a(e){n.catInfo.innerHTML=i(e)}function t(){return u(),b().then(r).catch(e=>m(e)).finally(()=>{f(),h()})}function r(e){o.setData(e.map(c=>({text:c.name,value:c.id})))}function i(e){return e.map(({url:c,breeds:y})=>{const[l]=y;return`
          <img src="${c}" alt="${l.name}" width="300">
          <div>
            <h3>${l.name}</h3>
            <p><strong>Description:</strong> ${l.description}</p>
            <p><strong>Temperament:</strong> ${l.temperament}</p>
          </div>
        `}).join("")}function u(){const e=document.querySelector(".loader");e.style.display="block"}function f(){const e=document.querySelector(".loader");e.style.display="none"}function h(){o.slim.container.style.display="block"}function m(e){console.error("Error:",e),p("Oops! Something went wrong! Try reloading the page!")}function p(e){g.error({title:"Error",message:e,position:"topRight"})}t()});
//# sourceMappingURL=commonHelpers.js.map
