import{a as u,i as g}from"./assets/vendor-6d0036ef.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="https://api.thecatapi.com/v1/breeds",b="live_1BhCbAxOfyNpYIgTYCWiXZS6lDLk1jq88WQSVrpMPuPstv7Ox0sVSsaxQgcHHrTK";u.defaults.headers.common["x-api-key"]=b;function v(){return u.get(S).then(n=>n.data)}function L(n){const i="https://api.thecatapi.com/v1/images/search";return u.get(i,{params:{breed_ids:n}}).then(s=>s.data)}document.addEventListener("DOMContentLoaded",function(){const n={breedSelect:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader")},i=new SlimSelect({select:n.breedSelect,placeholder:"Select a breed",showSearch:!0,searchText:"No matches found",searchPlaceholder:"Search...",searchHighlight:!0,searchFocus:!0,allowDeselect:!1,onChange:a});function s(e){n.catInfo.innerHTML=c(e)}function a(){const e=i.selected();e&&f(),L(e).then(o=>{o&&o.length>0?s(o):d("No cat data received or empty array!")}).catch(o=>m(o)).finally(()=>{e&&(h(),p())})}function t(){return f(),v().then(e=>{e&&e.length>0?r(e):d("No cat breeds received or empty array!")}).catch(e=>m(e)).finally(()=>{h(),p()})}function r(e){i.setData(e.map(o=>({text:o.name,value:o.id})))}function c(e){return e.map(({url:o,breeds:y})=>{const[l]=y;return`
          <img src="${o}" alt="${l.name}" width="300">
          <div>
            <h3>${l.name}</h3>
            <p><strong>Description:</strong> ${l.description}</p>
            <p><strong>Temperament:</strong> ${l.temperament}</p>
          </div>
        `}).join("")}function f(){n.loader.style.display="block"}function h(){n.loader.style.display="none"}function p(){i.slim.container.style.display="block"}function m(e){console.error("Error:",e),d("Oops! Something went wrong! Try reloading the page!")}function d(e){g.error({title:"Error",message:e,position:"topRight"})}t()});
//# sourceMappingURL=commonHelpers.js.map
