import{a as u}from"./assets/vendor-a61d8330.js";(function(){const c=document.createElement("link").relList;if(c&&c.supports&&c.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const b="https://api.thecatapi.com/v1/breeds",v="live_1BhCbAxOfyNpYIgTYCWiXZS6lDLk1jq88WQSVrpMPuPstv7Ox0sVSsaxQgcHHrTK";u.defaults.headers.common["x-api-key"]=v;function E(){return h(),u.get(b).then(e=>(m(),e.data)).catch(e=>{throw p(),console.error("Error fetching cat breeds:",e),e})}function w(e){const c="https://api.thecatapi.com/v1/images/search";return h(),u.get(c,{params:{breed_ids:e}}).then(n=>(m(),n.data)).catch(n=>{throw p(),console.error("Error fetching cat data by breed:",n),n})}function h(){document.querySelector(".loader").classList.add("visible")}function m(){document.querySelector(".loader").classList.remove("visible")}function p(){document.querySelector(".error").classList.add("visible")}document.addEventListener("DOMContentLoaded",function(){const e={breedSelect:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),error:document.querySelector(".error")},c=new SlimSelect({select:e.breedSelect,placeholder:"Select a breed",showSearch:!0,searchText:"No matches found",searchPlaceholder:"Search...",searchHighlight:!0,searchFocus:!0,allowDeselect:!1,onChange:function(){n()}});e.breedSelect.addEventListener("change",n);function n(){const o=c.selected();t(),w(o).then(l).catch(f).finally(r)}function l(o){e.catInfo.innerHTML=L(o)}function t(){e.loader.classList.add("loading")}function r(){e.loader.classList.remove("loading")}function i(){e.error.classList.add("visible")}function g(){e.error.classList.remove("visible")}function f(o){console.error(o),i()}function y(){return g(),t(),E().then(S).catch(f).finally(r)}function S(o){console.log(o),e.breedSelect.innerHTML="",o.forEach(s=>{const a=document.createElement("option");a.value=s.id,a.textContent=s.name,e.breedSelect.appendChild(a)}),c.setData(o.map(s=>({text:s.name,value:s.id})))}function L(o){return o.map(({url:s,breeds:a})=>{const[d]=a;return`
          <img src="${s}" alt="${d.name}" width="300">
          <div>
            <h3>${d.name}</h3>
            <p><strong>Description:</strong> ${d.description}</p>
            <p><strong>Temperament:</strong> ${d.temperament}</p>
          </div>
        `}).join("")}y()});
//# sourceMappingURL=commonHelpers.js.map
